#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'erb'
require 'yaml'

directory = 'licenses'

FileUtils.rm_rf(directory)
FileUtils.mkdir(directory)

version = ENV['VERSION'] ? "Version #{ENV['VERSION']}" : 'Working Draft'

meta = YAML.load_file('meta.yml')
template = ERB.new(File.read('template.erb.md'))
all_keys = meta.keys
meta.each do |key, properties|
  file = "#{properties['file']}.md"
  view = {}
  all_keys.each do |other_key|
    view[other_key] = other_key == key
  end
  view.merge!(properties)
  view['version'] = version
  text = template.result_with_hash(view)
  File.write("#{directory}/#{file}", text.gsub(/\n{2,}/, "\n\n"))
end
