#!/usr/bin/env ruby
# frozen_string_literal: true

require 'erb'
require 'yaml'

Dir.mkdir('licenses') rescue nil

meta = YAML.load_file('licenses.yml')
template = ERB.new(File.read('template.erb.md'))
all_keys = meta.keys
meta.each do |key, properties|
  file = "#{properties['file']}.md"
  view = {}
  all_keys.each do |other_key|
    view[other_key] = other_key == key
  end
  view.merge!(properties)
  text = template.result_with_hash(view)
  File.write("licenses/#{file}", text.gsub(/\n{2,}/, "\n\n"))
end
